# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

before_all do |lane, options|
	import_from_git(
		url: "git@github.com:doubleencore/POM-Fastlane-Tools.git",
		branch: "FTL-0003"
	)
end

platform :ios do

	desc "Description of what the lane does"
	lane :quick_test do
		token = ENV['APPBOT_TOKEN']
		value = appbot_build_number(
			api_token: token,
			name: "NOBU-iOS"
		)

		UI.message "Result: #{value}"
	end
end
